### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hijak** [dutchcoders/transfer.sh-web#5] opened 2017-11-07 13:58 UTC
Hi

after generating the webconifg and then specifying the path I get this error when viewing the url

`runtime error: invalid memory address or nil pointer dereference`

here is the output from grunt
```
~/projects/jack/trasweb
12:48 $ grunt build
Running "clean:dist" (clean) task
>> 19 paths cleaned.

Running "copy:server" (copy) task
Copied 4 files

Running "useminPrepare:html" (useminPrepare) task
Going through src/404.html, src/download.audio.html, src/download.code.html, src/download.html, src/download.image.html, src/download.markdown.html, src/download.sandbox.html, src/download.video.html, src/index.html to update the config
Looking for build script HTML comment blocks

Configuration is now:

  concat:
  { generated:
   { files:
      [ { dest: '.tmp/concat/scripts/vendor/modernizr.js',
          src: [ 'src/bower_components/modernizr/modernizr.js' ] },
        { dest: '.tmp/concat/scripts/main.js',
          src:
           [ 'src/bower_components/jquery/dist/jquery.js',
             'src/bower_components/uri.js/src/URI.min.js',
             'src/bower_components/bootstrap/js/transition.js',
             'src/bower_components/bootstrap/js/collapse.js',
             'src/scripts/showdown.js',
             'src/scripts/main.js' ] } ] } }

  uglify:
  { generated:
   { files:
      [ { dest: 'dist/scripts/vendor/modernizr.js',
          src: [ '.tmp/concat/scripts/vendor/modernizr.js' ] },
        { dest: 'dist/scripts/main.js',
          src: [ '.tmp/concat/scripts/main.js' ] } ] } }

  cssmin:
  { dist:
   { files:
      { '<%= yeoman.dist %>/styles/main.css': [ '.tmp/styles/{,*/}*.css', 'src/styles/{,*/}*.css' ] } } }

Running "concurrent:dist" (concurrent) task

    Running "htmlmin:dist" (htmlmin) task
    Minified dist/404.html 4.46 kB → 4.46 kB
    Minified dist/download.audio.html 1.17 kB → 1.19 kB
    Minified dist/download.code.html 4.88 kB → 4.87 kB
    Minified dist/download.html 630 B → 628 B
    Minified dist/download.image.html 1.07 kB → 1.08 kB
    Minified dist/download.markdown.html 984 B → 985 B
    Minified dist/download.sandbox.html 616 B → 619 B
    Minified dist/download.video.html 1.17 kB → 1.19 kB
    Minified dist/index.html 22.23 kB → 22.21 kB

    Done, without errors.


    Execution Time (2017-11-07 12:48:23 UTC)
    loading tasks    4ms  ▇▇ 3%
    htmlmin:dist   113ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 96%
    Total 118ms

    Running "imagemin:dist" (imagemin) task
    Minified 7 images (saved 17.01 kB)

    Done, without errors.


    Execution Time (2017-11-07 12:48:23 UTC)
    loading tasks    5ms  ▇ 1%
    imagemin:dist  380ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
    Total 386ms

    Running "less:dist" (less) task
    File src/styles/main.css.map created.
    File src/styles/main.css created: 125.13 kB → 125.18 kB

    Done, without errors.


    Execution Time (2017-11-07 12:48:23 UTC)
    less:dist    745ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
    Total 750ms

Running "cssmin:dist" (cssmin) task
File dist//styles/main.css created: 125.18 kB → 96.54 kB

Running "concat:generated" (concat) task
File .tmp/concat/scripts/vendor/modernizr.js created.
File .tmp/concat/scripts/main.js created.

Running "includes:build" (includes) task
>> Saved dist/404.html
>> Saved dist/download.audio.html
>> Saved dist/download.code.html
>> Saved dist/download.html
>> Saved dist/download.image.html
>> Saved dist/download.markdown.html
>> Saved dist/download.sandbox.html
>> Saved dist/download.video.html
>> Saved dist/index.html
>> Saved dist/includes/download-bottom.html
>> Saved dist/includes/download-btn.html
>> Saved dist/includes/download-top.html
>> Saved dist/includes/footer.html
>> Saved dist/includes/ga.html
>> Saved dist/includes/head.html
>> Saved dist/includes/js.html
>> Saved dist/includes/navigation.html

Running "uglify:generated" (uglify) task
>> 2 files created.

Running "copy:dist" (copy) task
Copied 20 files

Running "copy:server" (copy) task
Copied 4 files

Running "usemin:html" (usemin) task

Processing as HTML - dist/404.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.audio.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.code.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.image.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.markdown.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.sandbox.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/download.video.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/download-bottom.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/download-btn.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/download-top.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/footer.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/ga.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/head.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/js.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/includes/navigation.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Processing as HTML - dist/index.html
Update the HTML to reference our concat/min/revved script files
Update the HTML with the new css filenames
Update the HTML with the new img filenames
Update the HTML with the new video filenames
Update the HTML with the new poster filenames
Update the HTML with the new source filenames
Update the HTML with data-main tags
Update the HTML with data-* tags
Update the HTML with background imgs, case there is some inline style
Update the HTML with anchors images
Update the HTML with reference in input
Update the HTML with the new img filenames in meta tags
Update the HTML with the new object filenames
Update the HTML with the new image filenames for svg xlink:href links
Update the HTML with the new image filenames for src links

Running "usemin:css" (usemin) task

Processing as CSS - dist/styles/main.css
Update the CSS to reference our revved images

Done, without errors.


Execution Time (2017-11-07 12:48:22 UTC)
useminPrepare:html   58ms  ▇▇ 1%
concurrent:dist      1.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%
cssmin:dist          98ms  ▇▇ 2%
includes:build      147ms  ▇▇▇ 4%
uglify:generated       2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
copy:dist            70ms  ▇▇ 2%
usemin:html         184ms  ▇▇▇▇ 4%
Total 4.1s

~/projects/jack/trasweb
12:48 $ go generate
```

**Comment by goxofy** [comment] 2017-12-23 07:54
same error, I guess maybe the setting of web-path is wrong

**Comment by aspacca** [comment] 2018-06-26 17:02
@goxofy , @hijak still relevant?
I've just bumped transfer.sh-web master

**Comment by aspacca** [comment] 2018-06-27 19:42
duplicate of https://github.com/dutchcoders/transfer.sh/issues/91

will fix in transfer.sh repo

**Closed by aspacca** 2018-06-27 19:42 UTC
